{{- if .Values.secretProviderClass.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "application.fullnameOverride" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
  annotations:
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
{{- if .Values.initJob.enabled }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "2"
    "helm.sh/resource-policy": keep
{{- end }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  secretObjects:
  {{- if .Values.secretProviderClass.secrets }}
  - secretName: {{ include "application.fullnameOverride" . }}-secrets-provider-class # name of the Kubernetes secret object
    type: Opaque # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
    data:
  {{- range $key, $value := .Values.secretProviderClass.secrets }}
    - objectName: {{ $value }} # name of the mounted content to sync; this could be the object name or the object alias
      key: {{ $key }} # data field to populate
  {{- end }}
  {{- end }}
  {{- if .Values.secretProviderClass.tls.name }}
  - secretName: {{ include "application.fullnameOverride" . }}-tls-provider-class # name of the Kubernetes secret object
    type: kubernetes.io/tls # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
    data:
  {{- with .Values.secretProviderClass.tls }}
    - objectName: {{ .name }} # name of the mounted content to sync; this could be the object name or the object alias
      key: tls.key # data field to populate
    - objectName: {{ .name }} # name of the mounted content to sync; this could be the object name or the object alias
      key: tls.crt # data field to populate
  {{- end }}
  {{- end }}
  parameters:
    clientID: {{ .Values.secretProviderClass.clientID }}
    usePodIdentity: "false"
    keyvaultName: {{ .Values.secretProviderClass.vaultAddress }}
    tenantId: {{ .Values.secretProviderClass.tenant_id }}
    objects: |
      array:
      {{- if .Values.secretProviderClass.secrets }}
      {{- range $key, $value := .Values.secretProviderClass.secrets }}
        - |
          objectName: {{ $value }}
          objectType: secret
      {{- end }}
      {{- end }}
      {{- if .Values.secretProviderClass.tls.name }}
      {{- with .Values.secretProviderClass.tls }}
        - |
          objectName: {{ .name }}
          objectType: secret
          objectVersion: {{ .version | default "latest" | quote }}
      {{- end }}
      {{- end }}
{{- end }}
